CREATE TABLE public.issue (
	id int4 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	description varchar(255) NULL,
	link varchar(255) NULL,
	id_game int4 NULL,
	"key" varchar(255) NULL,
	title varchar(255) NULL,
	CONSTRAINT issue_pkey PRIMARY KEY (id),
	CONSTRAINT fkhopn6w32cau5xhnohdahv4snx FOREIGN KEY (id_game) REFERENCES public.game(id)
);