CREATE TABLE public.users (
	id int8 NOT NULL GENERATED BY DEFAULT AS IDENTITY,
	display_name varchar(255) NULL,
	email varchar(255) NULL,
	"password" varchar(255) NULL,
	"token" varchar(255) NULL,
	token_creation_date timestamp NULL,
	CONSTRAINT users_pkey PRIMARY KEY (id)
);